version: "3"
services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.3
    environment:
      - ELASTICSEARCH_HOST=http://elastic:9200
    ports:
      - 5601:5601
